services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: rcmd
    env_file:
      - .env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    ports:
      - "3000:3000"
    restart: unless-stopped
